//! Self-contained HTML audit report.
//!
//! Single file, no external CSS/JS — we want the artifact to work straight
//! from `file://` with no network, and remain trivially diff-able. Dark mode
//! is auto-switched via `prefers-color-scheme`.

use std::fmt::Write;

use crate::{events::Event, policy::Policy, stats::Stats, tamper::Diff};

/// Render the full report. The result is a complete `<!DOCTYPE html>`
/// document.
pub fn render(
    policy: &Policy,
    stats: &Stats,
    meta: ReportMeta<'_>,
    drift: Option<&Diff>,
) -> String {
    let mut html = String::with_capacity(16 * 1024);

    let by_kind = count_by_kind(&stats.samples);
    let badge_class = if stats.denied > 0 {
        "badge-danger"
    } else if stats.lost > 0 {
        "badge-warn"
    } else {
        "badge-ok"
    };
    let status_label = if stats.denied > 0 {
        format!("{} denied", stats.denied)
    } else if stats.lost > 0 {
        "events dropped".to_string()
    } else {
        "clean".to_string()
    };

    let _ = write!(
        html,
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>sakimori report — {title}</title>
<style>{css}</style>
</head>
<body>
<header class="top">
  <div class="brand">
    <span class="logo">🛡️</span>
    <span class="title">sakimori</span>
  </div>
  <div class="badges">
    <span class="badge mode-{mode_lc}">mode: {mode}</span>
    <span class="badge {badge_class}">{status_label}</span>
    <span class="badge">{observed} events</span>
  </div>
</header>

<main>
  <section class="stats">
    <div class="card"><div class="card-label">observed</div><div class="card-value">{observed}</div></div>
    <div class="card"><div class="card-label">denied</div><div class="card-value {denied_class}">{denied}</div></div>
    <div class="card"><div class="card-label">lost</div><div class="card-value {lost_class}">{lost}</div></div>
    <div class="card"><div class="card-label">kinds</div>
      <div class="card-kinds">
        <span class="chip chip-exec">exec · {n_exec}</span>
        <span class="chip chip-open">open · {n_open}</span>
        <span class="chip chip-connect">connect · {n_connect}</span>
      </div>
    </div>
  </section>
"#,
        title = html_escape(meta.title),
        css = CSS,
        mode = format!("{:?}", meta.mode).to_lowercase(),
        mode_lc = format!("{:?}", meta.mode).to_lowercase(),
        badge_class = badge_class,
        status_label = html_escape(&status_label),
        observed = stats.observed,
        denied = stats.denied,
        denied_class = if stats.denied > 0 { "danger" } else { "" },
        lost = stats.lost,
        lost_class = if stats.lost > 0 { "warn" } else { "" },
        n_exec = by_kind.exec,
        n_open = by_kind.open,
        n_connect = by_kind.connect,
    );

    // --- events table ---
    html.push_str(
        r#"  <section class="events">
    <div class="toolbar">
      <div class="tabs">
        <button class="tab active" data-filter="all">All</button>
        <button class="tab" data-filter="exec">Exec</button>
        <button class="tab" data-filter="open">Open</button>
        <button class="tab" data-filter="connect">Connect</button>
        <button class="tab" data-filter="denied">Denied</button>
      </div>
      <input id="q" type="search" placeholder="filter by path, host, comm…" autocomplete="off">
    </div>
    <table class="events-table">
      <thead><tr><th>verdict</th><th>kind</th><th>pid</th><th>comm</th><th>source</th><th>host</th><th>detail</th></tr></thead>
      <tbody>
"#,
    );

    for ev in &stats.samples {
        render_event_row(&mut html, ev);
    }

    html.push_str(
        r#"      </tbody>
    </table>
    <p class="hint">Showing up to 64 samples per kind. Full event stream is in the JSON log.</p>
  </section>

"#,
    );

    if let Some(d) = drift
        && !d.is_clean()
    {
        render_drift_section(&mut html, d);
    }

    html.push_str(
        r#"  <section class="policy">
    <h2>Effective policy</h2>
    <pre><code>"#,
    );
    let yaml = serde_yaml::to_string(policy).unwrap_or_else(|_| "# serialization error\n".into());
    html.push_str(&html_escape(&yaml));
    html.push_str(
        r#"</code></pre>
  </section>

  <footer>
    <div>Generated by <a href="https://github.com/bokuweb/sakimori">sakimori</a></div>
    <div class="meta">"#,
    );
    let _ = write!(html, "command: <code>{}</code>", html_escape(meta.command));
    html.push_str(
        r#"</div>
  </footer>
</main>
<script>"#,
    );
    html.push_str(JS);
    html.push_str("</script>\n</body>\n</html>\n");

    html
}

/// One-shot context passed in from the CLI.
pub struct ReportMeta<'a> {
    pub title: &'a str,
    pub mode: crate::policy::Mode,
    pub command: &'a str,
}

#[derive(Default)]
struct KindCounts {
    exec: u32,
    open: u32,
    connect: u32,
}

fn count_by_kind(samples: &[Event]) -> KindCounts {
    let mut c = KindCounts::default();
    for s in samples {
        match s {
            Event::Exec { .. } => c.exec += 1,
            Event::Open { .. } => c.open += 1,
            Event::Connect { .. } => c.connect += 1,
        }
    }
    c
}

fn render_event_row(out: &mut String, ev: &Event) {
    let denied = ev.denied();
    let row_class = if denied { "row-denied" } else { "" };
    let verdict_chip = if denied {
        r#"<span class="chip chip-deny">DENY</span>"#
    } else {
        r#"<span class="chip chip-allow">ALLOW</span>"#
    };
    // `host` is the resolved hostname for Connect events (PTR lookup
    // performed by the userspace supervisor) — empty for exec/open.
    let (kind, kind_class, pid, comm, host, detail) = match ev {
        Event::Exec {
            pid,
            comm,
            filename,
            argv0,
            ..
        } => (
            "exec",
            "chip-exec",
            *pid,
            comm.clone(),
            String::new(),
            format!(
                r#"<code>{}</code> <span class="muted">({})</span>"#,
                html_escape(filename),
                html_escape(argv0)
            ),
        ),
        Event::Open {
            pid,
            comm,
            filename,
            flags,
            ..
        } => (
            "open",
            "chip-open",
            *pid,
            comm.clone(),
            String::new(),
            format!(
                r#"<code>{}</code> <span class="muted">flags=0x{:x}</span>"#,
                html_escape(filename),
                flags
            ),
        ),
        Event::Connect {
            pid,
            comm,
            daddr,
            dport,
            hostname,
            ..
        } => {
            let host_cell = match hostname.as_deref().filter(|s| !s.is_empty()) {
                Some(h) => format!(r#"<code>{}</code>"#, html_escape(h)),
                None => r#"<span class="muted">—</span>"#.to_string(),
            };
            (
                "connect",
                "chip-connect",
                *pid,
                comm.clone(),
                host_cell,
                format!(r#"<code>{}:{}</code>"#, html_escape(daddr), dport),
            )
        }
    };
    let source_cell = render_source_cell(ev.source());
    // Searchable text used by the filter box. Includes both the
    // package-manager label and the root argv so users can grep
    // for "npm install foo" or just "npm".
    let source_search = ev
        .source()
        .map(|a| {
            let pm = a.package_manager.map(|p| p.label()).unwrap_or("");
            let argv = a.root_argv.as_deref().unwrap_or("");
            format!("{pm} {argv}")
        })
        .unwrap_or_default();
    let searchable = format!("{kind} {pid} {comm} {source_search} {host} {detail}").to_lowercase();
    let _ = write!(
        out,
        r#"        <tr class="{row_class}" data-kind="{kind}" data-denied="{denied}" data-search="{search}">
          <td>{verdict_chip}</td>
          <td><span class="chip {kind_class}">{kind}</span></td>
          <td class="num">{pid}</td>
          <td><code>{comm}</code></td>
          <td>{source_cell}</td>
          <td>{host}</td>
          <td>{detail}</td>
        </tr>
"#,
        row_class = row_class,
        kind = kind,
        denied = denied,
        search = html_escape(&searchable),
        verdict_chip = verdict_chip,
        kind_class = kind_class,
        pid = pid,
        comm = html_escape(&comm),
        source_cell = source_cell,
        host = host,
        detail = detail,
    );
}

/// Render the `source` column for one event. When attribution is
/// attached and a package manager was identified, show the label as
/// a chip with the joined argv as a hover tooltip — keeps the cell
/// compact while preserving the "what command actually ran this"
/// detail one mouse-over away. Falls back to em-dash when no
/// attribution is available (Linux-only feature; macOS/Windows
/// supervisor leaves source: None).
fn render_source_cell(attr: Option<&crate::attribution::Attribution>) -> String {
    let Some(a) = attr else {
        return r#"<span class="muted">—</span>"#.to_string();
    };
    let Some(pm) = a.package_manager else {
        // Have a chain but no recognised package manager — surface
        // the chain depth so the cell isn't blank.
        return format!(
            r#"<span class="muted" title="chain depth {}">—</span>"#,
            a.chain.len()
        );
    };
    let tooltip = a
        .root_argv
        .as_deref()
        .unwrap_or_else(|| pm.label())
        .chars()
        .take(200)
        .collect::<String>();
    format!(
        r#"<span class="chip chip-source" title="{tooltip}">{label}</span>"#,
        tooltip = html_escape(&tooltip),
        label = html_escape(pm.label()),
    )
}

/// Maximum drift rows surfaced per category before truncation.
/// Matches the step-summary cap so HTML and markdown views stay
/// in sync; the JSON log carries the full diff regardless.
const HTML_DRIFT_TOP_N: usize = 50;

fn render_drift_section(out: &mut String, drift: &Diff) {
    let total = drift.total();
    let _ = write!(
        out,
        r#"  <section class="drift">
    <h2>Workspace drift <span class="badge badge-warn">{total} change{plural}</span></h2>
    <p class="hint">Files modified during the supervised step.
       Compare against the baseline taken at <code>--snapshot-workspace</code>.</p>
    <table class="events-table">
      <thead><tr><th>change</th><th>path</th><th>note</th></tr></thead>
      <tbody>
"#,
        total = total,
        plural = if total == 1 { "" } else { "s" },
    );
    for p in drift.added.iter().take(HTML_DRIFT_TOP_N) {
        let _ = writeln!(
            out,
            r#"        <tr><td><span class="chip chip-add">added</span></td><td><code>{}</code></td><td></td></tr>"#,
            html_escape(&p.display().to_string())
        );
    }
    for m in drift.modified.iter().take(HTML_DRIFT_TOP_N) {
        let note = drift_modification_note(m);
        let _ = writeln!(
            out,
            r#"        <tr><td><span class="chip chip-mod">modified</span></td><td><code>{}</code></td><td><span class="muted">{}</span></td></tr>"#,
            html_escape(&m.path.display().to_string()),
            html_escape(&note),
        );
    }
    for p in drift.removed.iter().take(HTML_DRIFT_TOP_N) {
        let _ = writeln!(
            out,
            r#"        <tr><td><span class="chip chip-del">removed</span></td><td><code>{}</code></td><td></td></tr>"#,
            html_escape(&p.display().to_string())
        );
    }
    let shown = drift.added.len().min(HTML_DRIFT_TOP_N)
        + drift.modified.len().min(HTML_DRIFT_TOP_N)
        + drift.removed.len().min(HTML_DRIFT_TOP_N);
    out.push_str("      </tbody>\n    </table>\n");
    if total > shown {
        let _ = writeln!(
            out,
            r#"    <p class="hint">… {} more rows omitted; full diff is in <code>workspace_drift</code> of the JSON log.</p>"#,
            total - shown,
        );
    }
    out.push_str("  </section>\n\n");
}

fn drift_modification_note(m: &crate::tamper::ModifiedEntry) -> String {
    use crate::tamper::Entry;
    match (&m.before, &m.after) {
        (
            Entry::File {
                size: a,
                sha256: ha,
            },
            Entry::File {
                size: b,
                sha256: hb,
            },
        ) => {
            if a != b {
                format!("{a} → {b} bytes")
            } else if ha != hb {
                "contents changed".to_string()
            } else {
                "metadata changed".to_string()
            }
        }
        (Entry::Symlink { target: a }, Entry::Symlink { target: b }) => {
            format!("link target {a} → {b}")
        }
        _ => "type changed".to_string(),
    }
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

const CSS: &str = r#"
:root {
  --bg: #f7f8fa;
  --surface: #ffffff;
  --surface-2: #f1f3f7;
  --text: #18181b;
  --text-muted: #71717a;
  --border: #e4e4e7;
  --accent: #6366f1;
  --accent-soft: #e0e7ff;
  --danger: #dc2626;
  --danger-soft: #fee2e2;
  --warn: #d97706;
  --warn-soft: #fef3c7;
  --ok: #059669;
  --ok-soft: #d1fae5;
  --shadow: 0 1px 2px rgba(0,0,0,.04), 0 4px 12px rgba(0,0,0,.04);
  --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  --sans: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Inter, sans-serif;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #09090b;
    --surface: #18181b;
    --surface-2: #27272a;
    --text: #fafafa;
    --text-muted: #a1a1aa;
    --border: #27272a;
    --accent: #818cf8;
    --accent-soft: #312e81;
    --danger: #f87171;
    --danger-soft: #450a0a;
    --warn: #fbbf24;
    --warn-soft: #451a03;
    --ok: #34d399;
    --ok-soft: #064e3b;
    --shadow: 0 1px 2px rgba(0,0,0,.4), 0 4px 12px rgba(0,0,0,.3);
  }
}

* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  font-family: var(--sans);
  background: var(--bg);
  color: var(--text);
  font-size: 14px;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}
code, pre { font-family: var(--mono); font-size: 0.92em; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

.top {
  position: sticky; top: 0; z-index: 10;
  display: flex; justify-content: space-between; align-items: center;
  padding: 16px 32px;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  backdrop-filter: saturate(180%) blur(12px);
}
.brand { display: flex; gap: 10px; align-items: center; }
.brand .logo { font-size: 20px; }
.brand .title { font-weight: 700; font-size: 17px; letter-spacing: -0.01em; }
.badges { display: flex; gap: 8px; flex-wrap: wrap; }

.badge {
  display: inline-flex; align-items: center;
  padding: 4px 10px;
  border-radius: 999px;
  font-size: 12px; font-weight: 500;
  background: var(--surface-2);
  border: 1px solid var(--border);
  color: var(--text-muted);
}
.mode-block { background: var(--accent-soft); color: var(--accent); border-color: transparent; }
.mode-audit { background: var(--surface-2); color: var(--text-muted); }
.badge-ok { background: var(--ok-soft); color: var(--ok); border-color: transparent; }
.badge-danger { background: var(--danger-soft); color: var(--danger); border-color: transparent; font-weight: 600; }
.badge-warn { background: var(--warn-soft); color: var(--warn); border-color: transparent; }

main { max-width: 1200px; margin: 0 auto; padding: 32px; }

.stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 16px;
  margin-bottom: 32px;
}
.card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 20px;
  box-shadow: var(--shadow);
}
.card-label {
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--text-muted);
  font-weight: 600;
  margin-bottom: 8px;
}
.card-value {
  font-size: 34px; font-weight: 700;
  letter-spacing: -0.02em;
}
.card-value.danger { color: var(--danger); }
.card-value.warn { color: var(--warn); }
.card-kinds { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 4px; }

.chip {
  display: inline-flex; align-items: center;
  padding: 2px 8px;
  border-radius: 6px;
  font-size: 11px; font-weight: 600;
  background: var(--surface-2);
  color: var(--text-muted);
  font-family: var(--mono);
  letter-spacing: 0.02em;
}
.chip-allow { background: var(--ok-soft); color: var(--ok); }
.chip-deny { background: var(--danger-soft); color: var(--danger); }
.chip-exec { background: #ddd6fe; color: #6d28d9; }
.chip-open { background: #bfdbfe; color: #1d4ed8; }
.chip-connect { background: #fbcfe8; color: #be185d; }
.chip-source { background: var(--accent-soft); color: var(--accent); cursor: help; }
.chip-add { background: var(--ok-soft); color: var(--ok); }
.chip-mod { background: var(--warn-soft); color: var(--warn); }
.chip-del { background: var(--danger-soft); color: var(--danger); }
@media (prefers-color-scheme: dark) {
  .chip-exec { background: #4c1d95; color: #ddd6fe; }
  .chip-open { background: #1e3a8a; color: #bfdbfe; }
  .chip-connect { background: #831843; color: #fbcfe8; }
}

.drift { margin-bottom: 32px; }
.drift h2 { display: flex; gap: 12px; align-items: center; }

.events { margin-bottom: 32px; }
.toolbar {
  display: flex; justify-content: space-between; gap: 16px;
  align-items: center; margin-bottom: 12px; flex-wrap: wrap;
}
.tabs { display: flex; gap: 4px; background: var(--surface-2); padding: 3px; border-radius: 8px; }
.tab {
  border: 0; background: transparent; cursor: pointer;
  padding: 6px 14px; font-size: 13px; font-weight: 500;
  border-radius: 6px; color: var(--text-muted);
  font-family: var(--sans);
  transition: background 120ms, color 120ms;
}
.tab:hover { color: var(--text); }
.tab.active { background: var(--surface); color: var(--text); box-shadow: var(--shadow); }
#q {
  padding: 8px 14px;
  min-width: 260px;
  border: 1px solid var(--border);
  background: var(--surface);
  color: var(--text);
  border-radius: 8px;
  font-size: 13px;
  font-family: var(--sans);
  outline: none;
}
#q:focus { border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft); }

.events-table {
  width: 100%; border-collapse: collapse;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  overflow: hidden;
  box-shadow: var(--shadow);
}
.events-table th, .events-table td {
  padding: 10px 16px; text-align: left;
  border-bottom: 1px solid var(--border);
  vertical-align: middle;
}
.events-table th {
  background: var(--surface-2);
  font-size: 11px; text-transform: uppercase;
  letter-spacing: 0.08em; color: var(--text-muted);
  font-weight: 600;
}
.events-table tr:last-child td { border-bottom: 0; }
.events-table tr.row-denied { background: color-mix(in srgb, var(--danger-soft) 40%, transparent); }
.events-table .num { font-family: var(--mono); color: var(--text-muted); }
.events-table code { background: var(--surface-2); padding: 2px 6px; border-radius: 4px; }
.muted { color: var(--text-muted); }
.hint { color: var(--text-muted); font-size: 12px; margin-top: 8px; }

.policy pre {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 20px;
  overflow: auto;
  margin: 0;
  box-shadow: var(--shadow);
}
.policy h2 { font-size: 16px; margin: 0 0 12px 0; letter-spacing: -0.01em; }

footer {
  margin-top: 48px;
  padding: 24px 0;
  border-top: 1px solid var(--border);
  color: var(--text-muted);
  font-size: 12px;
  display: flex; justify-content: space-between; flex-wrap: wrap; gap: 8px;
}
footer code { background: var(--surface-2); padding: 2px 6px; border-radius: 4px; }
"#;

const JS: &str = r#"
(function() {
  const rows = document.querySelectorAll('.events-table tbody tr');
  const tabs = document.querySelectorAll('.tab');
  const q = document.getElementById('q');
  let filter = 'all';

  function apply() {
    const needle = q.value.trim().toLowerCase();
    for (const row of rows) {
      const kind = row.dataset.kind;
      const denied = row.dataset.denied === 'true';
      const hay = row.dataset.search || '';
      let kindOk = filter === 'all' || filter === kind || (filter === 'denied' && denied);
      let qOk = !needle || hay.includes(needle);
      row.style.display = (kindOk && qOk) ? '' : 'none';
    }
  }

  tabs.forEach(t => t.addEventListener('click', () => {
    tabs.forEach(x => x.classList.remove('active'));
    t.classList.add('active');
    filter = t.dataset.filter;
    apply();
  }));
  q.addEventListener('input', apply);
})();
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::{Mode, Policy};
    use crate::stats::Stats;

    fn stats_with_one_connect(daddr: &str, hostname: Option<&str>) -> Stats {
        let mut s = Stats::default();
        s.ingest(Event::Connect {
            pid: 42,
            uid: 0,
            comm: "curl".into(),
            daddr: daddr.into(),
            dport: 443,
            protocol: 6,
            denied: false,
            hostname: hostname.map(|s| s.to_string()),
            source: None,
        });
        s
    }

    fn meta<'a>() -> ReportMeta<'a> {
        ReportMeta {
            title: "test",
            mode: Mode::Audit,
            command: "curl https://example.com",
        }
    }

    #[test]
    fn html_includes_host_column_header() {
        let p = Policy::permissive_audit();
        let s = stats_with_one_connect("1.2.3.4", None);
        let out = render(&p, &s, meta(), None);
        assert!(out.contains("<th>host</th>"), "host column header missing");
    }

    #[test]
    fn connect_row_shows_hostname_when_present() {
        let p = Policy::permissive_audit();
        let s = stats_with_one_connect("1.2.3.4", Some("example.com"));
        let out = render(&p, &s, meta(), None);
        assert!(out.contains("example.com"), "hostname should render");
        // The IP still appears in the detail column.
        assert!(out.contains("1.2.3.4:443"));
    }

    #[test]
    fn connect_row_shows_dash_when_hostname_missing() {
        let p = Policy::permissive_audit();
        let s = stats_with_one_connect("1.2.3.4", None);
        let out = render(&p, &s, meta(), None);
        // Em-dash placeholder in the host cell.
        assert!(out.contains("—"), "dash placeholder expected when no PTR");
    }

    #[test]
    fn exec_and_open_rows_leave_host_empty_placeholder() {
        let p = Policy::permissive_audit();
        let mut s = Stats::default();
        s.ingest(Event::Exec {
            pid: 1,
            uid: 0,
            comm: "x".into(),
            filename: "/bin/sh".into(),
            argv0: "sh".into(),
            denied: false,
            source: None,
        });
        s.ingest(Event::Open {
            pid: 1,
            uid: 0,
            comm: "x".into(),
            filename: "/etc/passwd".into(),
            flags: 0,
            denied: false,
            source: None,
        });
        let out = render(&p, &s, meta(), None);
        // Both rows should render; the host cell is simply empty for
        // non-connect events.
        assert!(out.contains("/bin/sh"));
        assert!(out.contains("/etc/passwd"));
    }

    #[test]
    fn source_column_header_present() {
        let p = Policy::permissive_audit();
        let s = stats_with_one_connect("1.2.3.4", None);
        let out = render(&p, &s, meta(), None);
        assert!(out.contains("<th>source</th>"), "source column missing");
    }

    #[test]
    fn source_cell_shows_package_manager_label_when_attributed() {
        use crate::attribution::{Attribution, PackageManager, ProcInfo};
        let p = Policy::permissive_audit();
        let mut s = Stats::default();
        s.ingest(Event::Connect {
            pid: 1,
            uid: 0,
            comm: "curl".into(),
            daddr: "1.1.1.1".into(),
            dport: 443,
            protocol: 6,
            denied: false,
            hostname: None,
            source: Some(Attribution {
                chain: vec![ProcInfo {
                    pid: 1,
                    argv0: "npm".into(),
                    argv: "npm install left-pad@1.0.0".into(),
                }],
                package_manager: Some(PackageManager::Npm),
                root_argv: Some("npm install left-pad@1.0.0".into()),
            }),
        });
        let out = render(&p, &s, meta(), None);
        // Chip with the pm label rendered.
        assert!(
            out.contains(">npm<"),
            "expected pm chip with `npm` label, got:\n{out}"
        );
        // Tooltip carries the full argv for the cell hover.
        assert!(
            out.contains("npm install left-pad@1.0.0"),
            "expected root_argv in tooltip / search index"
        );
    }

    #[test]
    fn source_cell_falls_back_to_dash_when_no_attribution() {
        // Event without source → em-dash placeholder.
        let p = Policy::permissive_audit();
        let s = stats_with_one_connect("1.2.3.4", None);
        let out = render(&p, &s, meta(), None);
        // Both the host and source cells use the em-dash placeholder
        // — count >=2 to confirm the source cell got one too.
        assert!(
            out.matches("—").count() >= 2,
            "expected dash placeholders for missing data"
        );
    }

    #[test]
    fn drift_section_renders_only_when_drift_is_present() {
        use crate::tamper::{Diff, Entry, ModifiedEntry};
        use std::path::PathBuf;

        let p = Policy::permissive_audit();
        let s = Stats::default();

        // Clean diff → no section.
        let out = render(&p, &s, meta(), Some(&Diff::default()));
        assert!(!out.contains("Workspace drift"));

        // Real diff → section appears with chip rows.
        let drift = Diff {
            added: vec![PathBuf::from("src/new.rs")],
            modified: vec![ModifiedEntry {
                path: PathBuf::from("src/lib.rs"),
                before: Entry::File {
                    size: 100,
                    sha256: Some("a".repeat(64)),
                },
                after: Entry::File {
                    size: 200,
                    sha256: Some("b".repeat(64)),
                },
            }],
            removed: vec![PathBuf::from("src/old.rs")],
        };
        let out = render(&p, &s, meta(), Some(&drift));
        assert!(out.contains("Workspace drift"));
        assert!(out.contains("chip-add"));
        assert!(out.contains("chip-mod"));
        assert!(out.contains("chip-del"));
        // Modification note exposes the size delta.
        assert!(out.contains("100 → 200 bytes"));
    }
}
