//! Curated policy presets for Shai-Hulud-class supply-chain attacks.
//!
//! Each preset emits a `Policy` shape that the caller can either drop in
//! verbatim or merge into an existing policy file. Presets are
//! deliberately conservative — they only populate the dimension they're
//! named for (file deny for `persistence`, network deny for
//! `cloud-secret-egress`) so they compose cleanly with each other and
//! with hand-written policies.
//!
//! Output is a YAML string, not a [`Policy`] value, because we want to
//! interleave human-readable comments explaining *why* each rule is on
//! the list. A user staring at `~/Library/LaunchAgents/` in a deny list
//! months from now should be able to read the comment and know it's the
//! macOS user-persistence path, not delete the rule.
//!
//! File deny lists honour the kernel-side block cap
//! ([`sakimori_common::FILE_DENY_MAX_ENTRIES`] = 8). The `persistence`
//! preset is tuned to fit inside that cap so it can ship under
//! `mode: block` without the policy validator refusing to start.

use std::path::PathBuf;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Preset {
    /// File-write deny list covering common OS-level persistence paths
    /// (launchd, systemd, ssh, shell rc). Pairs with the v0.23
    /// attribution layer: a write to any of these from a
    /// package-manager-attributed subtree is the strongest possible
    /// "this install is malicious" signal.
    Persistence,
    /// Network deny list covering cloud-metadata endpoints and the
    /// well-known secret-store APIs. Built to ride on top of the
    /// proxy's SNI-based egress filter so rules match by the hostname
    /// the client asked for, not a CDN-rotated IP.
    CloudSecretEgress,
}

impl Preset {
    pub fn parse(name: &str) -> Option<Self> {
        match name {
            "persistence" => Some(Self::Persistence),
            "cloud-secret-egress" => Some(Self::CloudSecretEgress),
            _ => None,
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::Persistence => "persistence",
            Self::CloudSecretEgress => "cloud-secret-egress",
        }
    }
}

/// Resolve the home directory for the `persistence` preset.
///
/// The preset emits absolute paths because the policy YAML parser does
/// not expand `$HOME` / `~`. Callers that need a different home
/// (e.g. generating a policy for a CI runner from a developer laptop)
/// can pass it through `home_override`. When `None`, we read
/// `std::env::var("HOME")` and fall back to `/root` so the preset is
/// still emit-able in environments without HOME set (rare, but cron
/// jobs and minimal containers do this).
pub fn render(preset: Preset, home_override: Option<&str>) -> String {
    match preset {
        Preset::Persistence => render_persistence(home_override),
        Preset::CloudSecretEgress => render_cloud_secret_egress(),
    }
}

fn resolve_home(home_override: Option<&str>) -> String {
    if let Some(h) = home_override {
        return strip_trailing_slash(h);
    }
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    strip_trailing_slash(&home)
}

fn strip_trailing_slash(s: &str) -> String {
    let mut buf = PathBuf::from(s)
        .to_string_lossy()
        .trim_end_matches('/')
        .to_string();
    if buf.is_empty() {
        buf.push('/');
    }
    buf
}

fn render_persistence(home_override: Option<&str>) -> String {
    let home = resolve_home(home_override);
    // Keep this list at <= FILE_DENY_MAX_ENTRIES (8) so it fits in the
    // kernel-side block map. Each entry is prefix-matched against
    // open() paths with directory-boundary awareness, so `{home}/.ssh/`
    // matches `{home}/.ssh/authorized_keys` but not `{home}/.sshcfg`.
    let mut out = String::new();
    out.push_str(
        "# Generated by `sakimori policy preset persistence`.\n\
         # Curated file-write deny list for OS-level persistence paths.\n\
         # Pair with `sakimori run --policy persistence.yml` to SIGKILL\n\
         # any process — package-manager-attributed or not — that opens\n\
         # one of these for write. Audit-mode first to confirm nothing\n\
         # in your build legitimately touches them.\n\
         mode: audit\n\
         file:\n  default: allow\n  deny:\n",
    );
    let entries: [(&str, String); 8] = [
        ("SSH keys and authorized_keys", format!("{home}/.ssh/")),
        (
            "macOS user-scope launchd persistence",
            format!("{home}/Library/LaunchAgents/"),
        ),
        (
            "macOS system-scope launchd persistence (LaunchAgents)",
            "/Library/LaunchAgents/".to_string(),
        ),
        (
            "macOS root daemon persistence (LaunchDaemons)",
            "/Library/LaunchDaemons/".to_string(),
        ),
        (
            "Linux user-scope systemd unit dir",
            format!("{home}/.config/systemd/user/"),
        ),
        (
            "Linux system-scope systemd unit dir",
            "/etc/systemd/system/".to_string(),
        ),
        ("Shell rc — bash", format!("{home}/.bashrc")),
        ("Shell rc — zsh", format!("{home}/.zshrc")),
    ];
    for (why, path) in entries {
        out.push_str("    # ");
        out.push_str(why);
        out.push('\n');
        out.push_str("    - ");
        out.push_str(&path);
        out.push('\n');
    }
    out.push_str(
        "\n# Not on the list — covered well by other layers, or too\n\
         # noisy without a per-project allowlist:\n\
         #   - /etc/cron.d/, /var/spool/cron/  (rarely written by build steps,\n\
         #     but legitimate Linux packaging does — extend if your threat\n\
         #     model warrants it)\n\
         #   - ~/.bash_profile, ~/.zprofile, ~/.profile  (same surface as\n\
         #     ~/.bashrc / ~/.zshrc; drop them in if you can spare slots)\n\
         #   - .vscode/tasks.json, .claude/*.mjs  (workspace-local; the\n\
         #     workspace-drift snapshot is the better surface for these)\n",
    );
    out
}

fn render_cloud_secret_egress() -> String {
    let mut out = String::new();
    out.push_str(
        "# Generated by `sakimori policy preset cloud-secret-egress`.\n\
         # Network deny list for cloud-metadata + secret-store APIs.\n\
         #\n\
         # Designed to be enforced at the proxy layer (`sakimori proxy\n\
         # start --network-allow ...` plus the deny rules below) so the\n\
         # match runs against the hostname the client asked for, not a\n\
         # CDN-rotated IP. The eBPF connect path also picks these up\n\
         # for processes that bypass the proxy.\n\
         network:\n  default: allow\n  deny:\n",
    );
    let entries: &[(&str, &str)] = &[
        (
            "AWS / GCP / Azure IMDS magic IP (link-local, all three use it)",
            "169.254.169.254",
        ),
        ("GCP metadata service hostname", "metadata.google.internal"),
        (
            "AWS STS (AssumeRole, session credential mint)",
            "sts.amazonaws.com",
        ),
        (
            "AWS Secrets Manager (us-east-1; add other regions if used)",
            "secretsmanager.us-east-1.amazonaws.com",
        ),
        (
            "AWS Systems Manager Parameter Store (us-east-1)",
            "ssm.us-east-1.amazonaws.com",
        ),
        (
            "HashiCorp Vault default API hostname",
            "vault.service.consul",
        ),
        (
            "GitHub Actions OIDC token endpoint (commonly abused for token theft)",
            "vstoken.actions.githubusercontent.com",
        ),
    ];
    for (why, target) in entries {
        out.push_str("    # ");
        out.push_str(why);
        out.push('\n');
        out.push_str("    - target: ");
        out.push_str(target);
        out.push('\n');
    }
    out.push_str(
        "\n# Notes:\n\
         #   - Add the AWS regional endpoints you actually use (eu-west-1,\n\
         #     ap-northeast-1, ...). Wildcards in the middle of a target\n\
         #     are not supported; list each region explicitly.\n\
         #   - Azure IMDS is the same 169.254.169.254 entry above — the\n\
         #     `Metadata: true` header is checked, but at the network\n\
         #     layer the IP is what matters.\n\
         #   - For the SNI-based proxy path, the matcher also accepts\n\
         #     `*.example.com` subdomain wildcards; consider adding\n\
         #     `*.amazonaws.com` if you don't need any AWS egress at all.\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::{DefaultDecision, Mode, Policy};

    fn parse(yaml: &str) -> Policy {
        serde_yaml::from_str::<Policy>(yaml).expect("preset YAML must parse as Policy")
    }

    #[test]
    fn persistence_parses_and_is_audit_default() {
        let yaml = render(Preset::Persistence, Some("/home/x"));
        let policy = parse(&yaml);
        assert!(matches!(policy.mode, Mode::Audit));
        assert!(matches!(policy.file.default, DefaultDecision::Allow));
        assert_eq!(policy.file.deny.len(), 8);
    }

    #[test]
    fn persistence_expands_home() {
        let yaml = render(Preset::Persistence, Some("/home/alice"));
        assert!(yaml.contains("/home/alice/.ssh/"));
        assert!(yaml.contains("/home/alice/Library/LaunchAgents/"));
        assert!(!yaml.contains("$HOME"));
    }

    #[test]
    fn persistence_trims_trailing_slash_in_home() {
        let yaml = render(Preset::Persistence, Some("/home/bob/"));
        assert!(yaml.contains("/home/bob/.ssh/"));
        assert!(!yaml.contains("/home/bob//"));
    }

    #[test]
    fn persistence_fits_kernel_deny_cap() {
        use sakimori_common::FILE_DENY_MAX_ENTRIES;
        let yaml = render(Preset::Persistence, Some("/home/x"));
        let policy = parse(&yaml);
        assert!(policy.file.deny.len() <= FILE_DENY_MAX_ENTRIES as usize);
        // And the policy validates under mode: block (the kernel-side
        // cap is the only validator that touches preset output).
        policy
            .validate(Mode::Block)
            .expect("persistence preset must fit kernel cap under mode: block");
    }

    #[test]
    fn cloud_secret_egress_parses_and_has_deny_entries() {
        let yaml = render(Preset::CloudSecretEgress, None);
        let policy = parse(&yaml);
        assert!(matches!(policy.network.default, DefaultDecision::Allow));
        assert!(!policy.network.deny.is_empty());
        let targets: Vec<_> = policy
            .network
            .deny
            .iter()
            .map(|r| r.target.as_str())
            .collect();
        assert!(targets.contains(&"169.254.169.254"));
        assert!(targets.contains(&"sts.amazonaws.com"));
    }

    #[test]
    fn cloud_secret_egress_does_not_touch_file_or_process() {
        let yaml = render(Preset::CloudSecretEgress, None);
        let policy = parse(&yaml);
        assert!(policy.file.deny.is_empty());
        assert!(policy.file.allow.is_empty());
        assert!(policy.process.deny_exec.is_empty());
    }

    #[test]
    fn parse_name_round_trip() {
        assert_eq!(Preset::parse("persistence"), Some(Preset::Persistence));
        assert_eq!(
            Preset::parse("cloud-secret-egress"),
            Some(Preset::CloudSecretEgress)
        );
        assert_eq!(Preset::parse("nope"), None);
        assert_eq!(Preset::Persistence.name(), "persistence");
        assert_eq!(Preset::CloudSecretEgress.name(), "cloud-secret-egress");
    }
}
